import {GamePage} from "./gamepage.slint";
import {DownloadPage} from "./downloadpage.slint";
export MainWindow := Window {
    property<[StandardListViewItem]> gameList: [];
    property<int> currentPage: 1;
    property<bool> willRunInTerminal;
    property<int> selectedGame: -1;
    callback playButtonClicked;
    callback plusButtonClicked;
    callback downloadPageBackClicked;
    plusButtonClicked => {
        currentPage = 2;
    }
    downloadPageBackClicked => {
        currentPage = 1;
    }
    min-width: 420px;
    min-height: 400px;
    title: "Totem";
    GamePage {
        x: currentPage == 1 ? 0 : -1 * (parent.width + parent.x + 2px);
        animate x { duration: 125ms; easing: ease; }
        willRunInTerminal <=> root.willRunInTerminal; // idk how else to do this stuff
        selectedGame <=> root.selectedGame;
        gameList <=> root.gameList;
        playButtonClicked => { root.playButtonClicked(); }
        plusButtonClicked => { root.plusButtonClicked(); }
    }
    DownloadPage {
        x: currentPage == 2 ? 0 : parent.width + parent.x + 20px;
        animate x { duration: 125ms; easing: ease; }
        backButtonClicked => { root.downloadPageBackClicked(); }
    }
}